# Generated by Django 4.0 on 2021-12-27 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0002_post_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='username',
        ),
    ]
