# Generated by Django 4.0 on 2021-12-30 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0003_rename_title_post_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
