# Generated by Django 4.0 on 2021-12-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0006_alter_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='dateSubmitted',
            field=models.DateField(auto_now=True),
        ),
    ]
