# Generated by Django 4.0 on 2021-12-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0009_alter_post_datesubmitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateSubmitted',
            field=models.TextField(),
        ),
    ]
